sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
script:
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --reporter=dots --files=**/*.js
